name: E2E Test

on: [push, pull_request]

jobs:
  e2e-test:
    name: Node.js E2E Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["10.x", "12.x", "14.x"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm and Cypress
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies and verify Cypress
        run: |
          npm ci
          npm run cy:verify

      - name: Start MongoDB
        run: |
          docker run -d -p 27017:27017 mongo:4.0
          timeout 60s bash -c 'until nc -z localhost 27017; do sleep 2; done'

      - name: Run E2E test suite
        id: test-suite
        run: |
          NODE_ENV=test npm start -- --silent &
          npm run test:ci -- --config video=true

      - name: Prepare Cypress artifacts
        if: failure() && steps.test-suite.outcome == 'failure'
        run: |
          mkdir -p test/e2e/screenshots
          if [ -d "test/e2e/videos" ]; then
            cp -r test/e2e/videos/* test/e2e/screenshots/
          fi

      - name: Upload Cypress artifacts
        if: failure() && steps.test-suite.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts-node${{ matrix.node-version }}
          path: test/e2e/screenshots
