name: Lint

on:
  push:
    branches: [ main, team-zero/submission, backend, master ]
  pull_request:
    branches: [ main, team-zero/submission, backend, master ]

jobs:
  lint:
    name: Lint and Security Check
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install linting tools only
        run: npm install jshint@2.13.6 --no-save
        
      - name: Run linter
        run: npx jshint .
        
      - name: Check for secrets
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true